events {}
http {

    proxy_set_header Host $host;

    ssl_certificate /etc/certs/cer.pem;
    ssl_certificate_key /etc/certs/key.pem;

    # HTTP -> HTTPS Proxy
    # Security
#    server {
#        listen 80;
#        server_name _;
#
#        return 301 https://$host$request_uri;
#    }

    server {
        server_name _;
        listen 443 ssl;

        include /etc/nginx/mime.types;

        location / {
            try_files $uri $uri/ /index.html;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Prefix /;
        }

#        location /api/ {
#            proxy_pass http://some-container:5000/;
#            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_set_header X-Forwarded-Proto $scheme;
#            proxy_set_header X-Forwarded-Host $host;
#            proxy_set_header X-Forwarded-Prefix /;
#        }
    }

    # HTTP Docker Only
    # Infrastructure
    server {
        server_name _;
        listen 80;

        allow 172.0.0.0/8;
        allow 127.0.0.1; # 4healthcheck

        deny all;

        location / {
        }
    }

    # PGAdmin
    server {
        server_name pgadmin.localhost.company.com;
        resolver 127.0.0.11 valid=30s;
        listen 443 ssl;

        set $target "http://pgadmin:80";        

        location / {
            proxy_pass $target;
        }
    }

    # Jenkins
#    server {
#        server_name jenkins.localhost.company.com;
#        listen 8443 ssl;
#        listen 80;

#        set $target "http://jenkins-container-name:8080";

#        location / {
#            proxy_set_header   X-Real-IP         $remote_addr;
#            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
#            proxy_set_header   X-Forwarded-Proto $scheme;
#            
#            proxy_pass $target;
#        }
#    }
}